import type { HouseholdSnapshot } from './householdRecords';
import { expenseCategoryLabel } from './expenseCategories';
import { displayDate } from './familyRecords';
const escape = (value:unknown) => String(value ?? '-').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const money = (value?:number) => value === undefined ? '-' : new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(value);
export function monthlyReport(snapshot:HouseholdSnapshot, month:string, generatedAt=new Date()) {
  if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(month))throw new Error('Bulan tidak valid');
  const records=snapshot.records;
  const expenses=records.expenses.filter(e=>e.expenseDate.startsWith(month)).sort((a,b)=>a.expenseDate.localeCompare(b.expenseDate));
  const appointments=records.appointments.filter(a=>a.appointmentDate.startsWith(month)).sort((a,b)=>a.appointmentDate.localeCompare(b.appointmentDate));
  const documents=records.documents.filter(d=>d.documentDate?.startsWith(month));
  const total=expenses.reduce((sum,e)=>sum+e.paidAmount,0);
  const groups=new Map<string,number>();for(const e of expenses){const label=expenseCategoryLabel(e.category);groups.set(label,(groups.get(label)||0)+e.paidAmount);}
  const table=(headers:string[],rows:unknown[][])=>rows.length?'<div class="table-wrap"><table><thead><tr>'+headers.map(h=>'<th>'+escape(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map(cell=>'<td>'+escape(cell)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>':'<p class="empty">Tidak ada catatan.</p>';
  const section=(title:string,description:string,headers:string[],rows:unknown[][])=>'<section><h2>'+title+'</h2><p class="caption">'+description+'</p>'+table(headers,rows)+'</section>';
  const period=new Intl.DateTimeFormat('id-ID',{month:'long',year:'numeric',timeZone:'Asia/Jakarta'}).format(new Date(month+'-01T12:00:00+07:00'));
  return '<!doctype html><html lang="id"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Laporan Little Journey '+escape(month)+'</title><style>body{margin:0;background:#f8f7fc;color:#292442;font:14px/1.6 system-ui,sans-serif}main{max-width:1000px;margin:32px auto;padding:32px;background:white;border-radius:24px}header{padding:28px;border-radius:20px;background:linear-gradient(120deg,#34236b,#6c4cf5);color:white}h1{margin:8px 0;font-size:30px}h2{font-size:19px;margin-bottom:4px}.caption,.empty,footer{color:#716b82;font-size:12px}.summary{display:flex;flex-wrap:wrap;gap:14px;margin:24px 0}.summary div{flex:1;min-width:160px;background:#eee9ff;padding:18px;border-radius:16px}.summary strong{display:block;font-size:22px}section{margin:28px 0}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse}th{text-align:left;background:#f5f3fa;font-size:12px}td,th{padding:12px;border-bottom:1px solid #ebe6f2;vertical-align:top;overflow-wrap:anywhere}button{background:#6c4cf5;color:white;border:0;border-radius:12px;padding:12px 18px;cursor:pointer;margin-bottom:16px}@media(max-width:600px){main{margin:0;padding:16px;border-radius:0}td,th{padding:8px;min-width:85px}}@media print{body{background:white}main{margin:0;padding:0;max-width:none}button{display:none}header{-webkit-print-color-adjust:exact;print-color-adjust:exact}.table-wrap{overflow:visible}tr{break-inside:avoid}thead{display:table-header-group}td,th{min-width:0}}</style><main><button onclick="window.print()">Cetak / Simpan PDF</button><header><span>LITTLE JOURNEY · LAPORAN BULANAN</span><h1>'+escape(period)+'</h1><div>'+escape(snapshot.householdName)+'</div></header><div class="summary"><div>Pengeluaran bulan ini<strong>'+money(total)+'</strong></div><div>Transaksi<strong>'+expenses.length+'</strong></div><div>Jadwal bulan ini<strong>'+appointments.length+'</strong></div></div>'
  +section('Pengeluaran per kategori','Dihitung hanya dari transaksi bulan terpilih.',['Kategori','Total'],[...groups].map(([c,v])=>[c,money(v)]))
  +section('Riwayat pengeluaran','Termasuk pembelian belanja; setiap transaksi dihitung satu kali.',['Tanggal','Uraian','Kategori','Nominal','Catatan / lampiran'],expenses.map(e=>[displayDate(e.expenseDate),e.title,expenseCategoryLabel(e.category),money(e.paidAmount),[e.notes,e.attachment?.name].filter(Boolean).join(' · ')]))
  +section('Jadwal','Berdasarkan tanggal jadwal pada bulan terpilih.',['Tanggal / jam','Tujuan','Dokter','Lokasi','Catatan'],appointments.map(a=>[displayDate(a.appointmentDate)+' '+(a.appointmentTime||''),a.purpose,a.doctor,a.hospital,a.notes]))
  +section('Dokumen bulan ini','Berdasarkan tanggal dokumen, bukan tanggal unggah. File asli tidak disertakan.',['Tanggal','Judul','Jenis','Nama file','Catatan'],documents.map(d=>[displayDate(d.documentDate!),d.title,d.documentType,d.attachment?.name,d.notes]))
  +section('Checklist — kondisi saat diunduh','Semua item saat ini. Riwayat perubahan status bulanan belum dicatat.',['Item','Kategori','Status','Catatan'],snapshot.tasks.map(t=>[t.name,t.category,({Completed:'Selesai',Pending:'Belum selesai','In Progress':'Dikerjakan',Skipped:'Dilewati'} as Record<string,string>)[t.status],t.notes]))
  +section('Belanja — kondisi saat diunduh','Semua barang saat ini. Pembelian bulan terpilih juga tercantum pada pengeluaran.',['Barang / varian','Status','Perkiraan','Harga beli','Tanggal beli','Link / catatan'],records.shoppingItems.map(i=>[[i.item,i.brand,i.model].filter(Boolean).join(' · '),({Bought:'Dibeli',Received:'Diterima',Wishlist:'Belum dibeli',Skip:'Dilewati'} as Record<string,string>)[i.status]||i.status,money(i.estimatedPrice),money(i.actualPurchasePrice),i.purchaseDate?displayDate(i.purchaseDate):'-',[i.productUrl,i.notes].filter(Boolean).join(' · ')]))
  +section('Budget — kondisi saat diunduh','Budget keluarga keseluruhan, bukan budget bulanan.',['Total budget','Total pengeluaran tersimpan','Sisa budget'],[[snapshot.budgetConfigured?money(snapshot.totalBudget):'Belum diatur',money(records.expenses.reduce((s,e)=>s+e.paidAmount,0)),snapshot.budgetConfigured?money(snapshot.totalBudget-records.expenses.reduce((s,e)=>s+e.paidAmount,0)):'-']])
  +'<footer>Dibuat '+escape(new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Jakarta'}).format(generatedAt))+' WIB. Laporan berisi catatan yang masih tersimpan saat diunduh; bukan audit log atau backup file lampiran. Dokumen tanpa tanggal tidak masuk bagian bulanan ('+records.documents.filter(d=>!d.documentDate).length+' dokumen). Simpan ekspor data lengkap untuk salinan semua catatan.</footer></main></html>';
}
export function downloadReportFile(name:string, content:string, type:string) {
  const url=URL.createObjectURL(new Blob([content],{type}));const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
