import React from 'react';
import { Appointment } from '../../types/domain';
import { PipMascot } from '../mascot/PipMascot';
import { Clock, MapPin, Stethoscope, Plus } from 'lucide-react';
import { displayDate } from '../../lib/familyRecords';
import { RecordActions } from '../records/RecordEditor';
interface Props { appointments: Appointment[]; onAddAppointment: () => void; onEdit: (item: Appointment) => void; onDelete: (item: Appointment) => void; }
export const AppointmentsView: React.FC<Props> = ({ appointments, onAddAppointment, onEdit, onDelete }) => <div className="space-y-4 px-4 pb-28 pt-2 max-w-4xl mx-auto">
  <section className="bg-white rounded-[28px] p-5 sm:p-6 border border-[#F0ECE4] shadow-xs flex items-center justify-between"><div><span className="text-[10px] font-black uppercase tracking-wider text-[#6C4CF5] bg-[#EEE9FF] px-2.5 py-0.5 rounded-full">Jadwal Keluarga</span><h1 className="text-xl sm:text-2xl font-black text-[#292442] mt-1.5">Jadwal Kontrol Dokter</h1><p className="text-xs font-bold text-[#79738E] mt-0.5">{appointments.length} jadwal terdaftar</p></div><PipMascot mood="happy" size={60} /></section>
  {appointments.length === 0 && <p className="p-5 bg-white rounded-[24px] text-sm text-[#79738E]">Belum ada jadwal kontrol.</p>}
  {appointments.map(apt => <article key={apt.id} className="bg-white rounded-[24px] p-5 border border-[#F0ECE4] shadow-xs"><div className="flex items-start justify-between gap-3"><div className="flex items-start gap-3"><div className="w-12 h-12 rounded-2xl bg-[#E7FAF5] text-[#1EA896] flex items-center justify-center shrink-0"><Stethoscope className="w-6 h-6" /></div><div><span className="text-xs font-black text-[#1EA896] bg-[#E7FAF5] px-2.5 py-1 rounded-full inline-flex items-center gap-1"><Clock className="w-3.5 h-3.5" />{displayDate(apt.appointmentDate)}{apt.appointmentTime && ` • ${apt.appointmentTime}`}</span><h2 className="text-base font-black text-[#292442] mt-2">{apt.purpose}</h2>{apt.doctor && <p className="text-xs font-bold text-[#6C4CF5] mt-1">{apt.doctor}</p>}{apt.hospital && <p className="text-xs font-semibold text-[#79738E] mt-1 flex items-center gap-1"><MapPin className="w-3.5 h-3.5" />{apt.hospital}</p>}{apt.stage === 'pregnancy' && apt.targetGestationalWeek && <p className="mt-1 text-xs text-[#79738E]">Minggu ke-{apt.targetGestationalWeek}</p>}</div></div><RecordActions onEdit={() => onEdit(apt)} onDelete={() => onDelete(apt)} /></div>{apt.notes && <p className="mt-3 text-xs font-semibold text-[#5A556B] bg-[#FCFBF8] p-3 rounded-xl border border-[#F0ECE4]">{apt.notes}</p>}</article>)}
  <button onClick={onAddAppointment} className="w-full py-3.5 rounded-2xl bg-[#EEE9FF] text-[#6C4CF5] font-black text-sm flex items-center justify-center gap-2"><Plus className="w-4 h-4" />Tambah Jadwal</button>
</div>;
