import { attachmentLabel } from '../../lib/uploadImage';
import { expenseCategoryLabel } from '../../lib/expenseCategories';
import React from 'react';
import { formatIDR } from '../../data/mockData';
import { BudgetCalculationResult } from '../../lib/businessLogic';
import { categorySpending, displayDate } from '../../lib/familyRecords';
import { Expense, ShoppingItem } from '../../types/domain';
import { PipMascot } from '../mascot/PipMascot';
import { RecordActions } from '../records/RecordEditor';
interface Props {
  isBudgetConfigured: boolean;
  onAddExpense: () => void; onOpenBudgetSetup: () => void; budgetSummary: BudgetCalculationResult;
  categoryAllocations: Array<{ category: string; planned: number; icon: string; color: string }>;
  shoppingItems?: ShoppingItem[]; expenses?: Expense[];
  onEditExpense: (expense: Expense) => void; onDeleteExpense: (expense: Expense) => void; onViewExpense: (expense: Expense) => void;
}
export const BudgetView: React.FC<Props> = ({ isBudgetConfigured, onAddExpense, onOpenBudgetSetup, budgetSummary, shoppingItems = [], expenses = [], onEditExpense, onDeleteExpense, onViewExpense }) => {
  const categories = categorySpending(expenses);
  const unpaid = expenses.filter(e => e.totalAmount > e.paidAmount);
  const planned = shoppingItems.filter(i => i.status !== 'Bought' && i.status !== 'Received' && i.status !== 'Skip' && !expenses.some(e => e.shoppingItemId === i.id));
  const history = [...expenses].sort((a, b) => b.expenseDate.localeCompare(a.expenseDate));
  return <div className="space-y-4 px-4 pb-28 pt-2 max-w-4xl mx-auto">
    <div className="flex items-center justify-between gap-2"><h1 className="text-xl sm:text-2xl font-black text-[#292442]">Budget Keluarga</h1><button onClick={onOpenBudgetSetup} className="px-3 py-2 rounded-xl border border-[#E9E4DC] bg-white text-xs font-black text-[#34236B]">Atur Budget</button></div>
    {!isBudgetConfigured && <p className="p-4 rounded-2xl bg-white text-sm text-[#79738E]">Atur budget pertama kamu. Total budget belum dikonfigurasi.</p>}
    <section aria-label="Ringkasan Budget" className="rounded-[30px] bg-gradient-to-br from-[#34236B] to-[#6C4CF5] p-5 sm:p-6 text-white shadow-xl"><div className="flex items-center justify-between mb-4"><span className="text-xs font-black uppercase tracking-wider">Budget Persiapan</span><PipMascot mood="proud" size={54} /></div><div className="grid grid-cols-1 sm:grid-cols-3 gap-4">{[['Total Budget', budgetSummary.totalBudget], ['Sudah Keluar', budgetSummary.actualPaid], ['Sisa Budget', budgetSummary.remainingBudget]].map(([label, value]) => <div key={String(label)}><span className="block text-xs font-bold text-white/75">{label}</span><span className="block mt-1 text-xl font-black">{!isBudgetConfigured && label !== 'Sudah Keluar' ? '-' : formatIDR(Number(value))}</span></div>)}</div><p className="mt-4 text-xs font-bold">{isBudgetConfigured ? `${budgetSummary.spentPercentage}% terpakai` : 'Persentase belum tersedia: budget belum diatur'}</p><div role="progressbar" aria-label="Budget terpakai" aria-valuenow={budgetSummary.spentPercentage} aria-valuemin={0} aria-valuemax={100} className="mt-2 h-3 rounded-full bg-black/20 overflow-hidden"><div className="h-full rounded-full bg-gradient-to-r from-[#FFD45A] to-[#52D6C7]" style={{ width: `${Math.max(0, Math.min(100, budgetSummary.spentPercentage))}%` }} /></div><p className="mt-3 text-[11px] text-white/80">Sudah keluar berasal dari Riwayat Pengeluaran. Sisa budget = total budget − sudah keluar.</p></section>
    <div className="flex flex-wrap gap-2"><button onClick={onAddExpense} className="px-4 py-3 rounded-2xl bg-[#EEE9FF] text-[#6C4CF5] text-xs font-black">Catat Pengeluaran</button><a href="#expense-history" className="px-4 py-3 rounded-2xl bg-white border border-[#E7E2D8] text-[#34236B] text-xs font-black">Riwayat Pengeluaran</a></div>
    <section className="bg-white rounded-[28px] p-5 border border-[#F0ECE4] shadow-xs"><h2 className="text-base font-black text-[#292442]">Pengeluaran per Kategori</h2><div className="mt-3 space-y-2">{categories.length ? categories.map(c => <div key={c.category} className="flex justify-between gap-3 py-2 border-b border-[#F5F2EA] text-sm"><span className="font-bold text-[#79738E]">{expenseCategoryLabel(c.category)}</span><span className="font-black text-[#34236B]">{formatIDR(c.amount)}</span></div>) : <p className="text-sm text-[#79738E]">Belum ada pengeluaran.</p>}</div></section>
    {(unpaid.length > 0 || planned.length > 0) && <section className="bg-white rounded-[28px] p-5 border border-[#F0ECE4]"><h2 className="text-base font-black text-[#292442]">Rencana Belum Terealisasi</h2><div className="mt-3 space-y-2">{unpaid.map(e => <div key={e.id} className="flex justify-between gap-3 text-xs font-bold text-[#79738E]"><span>{e.title} • sisa pembayaran</span><span>{formatIDR(e.totalAmount - e.paidAmount)}</span></div>)}{planned.map(i => <div key={i.id} className="flex justify-between gap-3 text-xs font-bold text-[#79738E]"><span>{i.item} • perkiraan</span><span>{i.estimatedPrice == null ? '-' : formatIDR(i.estimatedPrice)}</span></div>)}</div><p className="mt-3 text-[11px] text-[#79738E]">Nilai perkiraan ini belum dihitung sebagai pengeluaran.</p></section>}
    <section id="expense-history" className="scroll-mt-20 bg-white rounded-[28px] p-5 border border-[#F0ECE4] shadow-xs"><h2 className="text-base font-black text-[#292442]">Riwayat Pengeluaran</h2><p className="mt-1 text-xs text-[#79738E]">{expenses.length} transaksi • termasuk pembelian barang</p><div className="mt-4 space-y-3">{history.length === 0 && <p className="text-sm text-[#79738E]">Belum ada transaksi. Pengeluaran yang dicatat akan muncul di sini.</p>}{history.map(e => <article key={e.id} className="p-3 rounded-2xl bg-[#FCFBF8] border border-[#E7E2D8]"><div className="flex items-start justify-between gap-3"><button onClick={() => onViewExpense(e)} className="text-left min-w-0"><p className="text-[11px] text-[#79738E] font-bold">{displayDate(e.expenseDate)} • {expenseCategoryLabel(e.category)}</p><h3 className="mt-1 text-sm font-black text-[#292442]">{e.title}</h3><p className="mt-1 text-sm font-black text-[#34236B]">{formatIDR(e.paidAmount)}</p>{e.attachment && <p className="mt-1 text-xs text-[#6C4CF5]">📎 {attachmentLabel(e.attachment)}</p>}</button><RecordActions onEdit={() => onEditExpense(e)} onDelete={() => onDeleteExpense(e)} extra={<button onClick={() => onViewExpense(e)} className="block w-full text-left p-3 text-[#34236B]">Lihat Detail</button>} /></div>{e.attachment && <button onClick={() => onViewExpense(e)} className="mt-2 text-xs font-black text-[#6C4CF5]">Lihat Lampiran</button>}</article>)}</div></section>
  </div>;
};
