import React, { useState } from 'react';
import { Expense, ShoppingItem } from '../../types/domain';
import { formatIDR } from '../../data/mockData';
import { isSafeShoppingUrl, isShoppingPrice } from '../../lib/shopping';
import { displayDate, shoppingSpend } from '../../lib/familyRecords';
import { PipMascot } from '../mascot/PipMascot';
import { RecordActions, fieldClass, labelClass, buttonClass } from '../records/RecordEditor';
import { ExternalLink, Plus } from 'lucide-react';
interface Props { items: ShoppingItem[]; expenses: Expense[]; onAddItem: () => void; onEdit: (item: ShoppingItem) => void; onDelete: (item: ShoppingItem) => void; onBuy: (id: string, price: number, date: string) => void; onReverse: (item: ShoppingItem) => void; }
export const ShoppingView: React.FC<Props> = ({ items, expenses, onAddItem, onEdit, onDelete, onBuy, onReverse }) => {
  const [filter, setFilter] = useState('all');
  const [purchase, setPurchase] = useState<{ id: string; price: string; date: string } | null>(null);
  const bought = (i: ShoppingItem) => i.status === 'Bought' || i.status === 'Received';
  const boughtCount = items.filter(bought).length;
  const remaining = items.filter(i => !bought(i) && i.status !== 'Skip').length;
  const filtered = items.filter(i => filter === 'all' || (filter === 'bought' ? bought(i) : !bought(i) && i.status !== 'Skip'));
  const purchasePrice = purchase?.price.trim() ? Number(purchase.price) : undefined;
  return <div className="space-y-4 px-4 pb-28 pt-2 max-w-4xl mx-auto">
    <section className="bg-white rounded-[28px] p-5 sm:p-6 border border-[#F0ECE4] shadow-xs"><div className="flex justify-between items-center"><div><span className="text-[10px] font-black uppercase tracking-wider text-[#6C4CF5] bg-[#EEE9FF] px-2.5 py-0.5 rounded-full">Wishlist Keluarga</span><h1 className="text-xl sm:text-2xl font-black text-[#292442] mt-1.5">Belanja Kebutuhan Keluarga</h1></div><PipMascot mood={remaining === 0 && items.length ? 'celebrate' : 'proud'} size={60} /></div><div className="grid grid-cols-3 gap-2 mt-4">{[['Sudah Dibeli', `${boughtCount} barang`], ['Belum Dibeli', `${remaining} barang`], ['Total Belanja', formatIDR(shoppingSpend(expenses))]].map(([label, value]) => <div key={label} className="bg-[#FAF8F5] p-3 rounded-2xl border border-[#F0ECE4]"><span className="text-[10px] font-bold text-[#79738E] block">{label}</span><span className="text-sm sm:text-lg font-black text-[#34236B] block mt-1 break-words">{value}</span></div>)}</div><p className="mt-2 text-[11px] text-[#79738E]">Total belanja berasal dari transaksi pembelian di Riwayat Pengeluaran, termasuk barang yang sudah dihapus.</p></section>
    <div role="tablist" aria-label="Filter Status Belanja" className="flex gap-2">{[['all', 'Semua'], ['pending', 'Belum Dibeli'], ['bought', 'Dibeli']].map(([key, label]) => <button key={key} role="tab" aria-selected={filter === key} onClick={() => setFilter(key)} className={`px-4 py-2 rounded-full text-xs font-black ${filter === key ? 'bg-[#34236B] text-white' : 'bg-white text-[#79738E] border border-[#EBE6DC]'}`}>{label}</button>)}</div>
    {filtered.length === 0 && <p className="p-5 rounded-[24px] bg-white text-sm text-[#79738E]">Belum ada barang di filter ini.</p>}
    {filtered.map(item => <article key={item.id} className="bg-white rounded-[26px] p-5 border border-[#F0ECE4] shadow-xs"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-[10px] font-bold text-[#79738E]">{[item.brand, item.category, item.stage === 'pregnancy' && item.targetGestationalWeek ? `Minggu ${item.targetGestationalWeek}` : '', item.targetDate ? `Target ${displayDate(item.targetDate)}` : ''].filter(Boolean).join(' • ')}</p><h2 className="text-base font-black text-[#292442] mt-1">{item.item}</h2>{item.model && <p className="text-xs text-[#79738E] mt-1">{item.model}</p>}</div><RecordActions onEdit={() => onEdit(item)} onDelete={() => onDelete(item)} /></div>
      <div className="mt-3 pt-3 border-t border-[#F5F2EA] flex items-end justify-between flex-wrap gap-3"><div><span className="text-[10px] font-bold text-[#79738E] block">{bought(item) ? 'Harga Beli' : 'Harga Perkiraan'}</span><span className="text-base font-black text-[#34236B]">{bought(item) ? formatIDR(item.actualPurchasePrice ?? item.actualPrice! * (item.quantity || 1)) : isShoppingPrice(item.estimatedPrice) ? formatIDR(item.estimatedPrice) : '-'}</span>{bought(item) && <p className="text-[11px] text-[#79738E] mt-1">{displayDate(item.purchaseDate)}</p>}</div><div className="flex gap-2">{item.productUrl && isSafeShoppingUrl(item.productUrl) && <a href={item.productUrl} target="_blank" rel="noopener noreferrer" className="px-3 py-2 rounded-xl bg-[#FAF8F5] text-[#79738E] text-xs font-black inline-flex items-center gap-1"><ExternalLink className="w-3.5 h-3.5" />Buka Link</a>}<button onClick={() => bought(item) ? onReverse(item) : setPurchase({ id: item.id, price: '', date: '' })} className={`px-3 py-2 rounded-xl text-xs font-black ${bought(item) ? 'bg-[#E7FAF5] text-[#1EA896]' : 'bg-[#34236B] text-white'}`}>{bought(item) ? 'Dibeli' : 'Tandai Beli'}</button></div></div>
      {purchase?.id === item.id && !bought(item) && <form className="mt-3 p-3 rounded-2xl bg-[#FCFBF8] border border-[#E7E2D8] space-y-3" onSubmit={e => { e.preventDefault(); if (!isShoppingPrice(purchasePrice) || !purchase.date) return; onBuy(item.id, purchasePrice, purchase.date); setPurchase(null); }}><div><label htmlFor={`buy-price-${item.id}`} className={labelClass}>Harga Beli (IDR) *</label><input id={`buy-price-${item.id}`} type="number" required min="0" step="1" value={purchase.price} onChange={e => setPurchase({ ...purchase, price: e.target.value })} placeholder="Masukkan 0 hanya jika gratis" className={fieldClass} /></div><div><label htmlFor={`buy-date-${item.id}`} className={labelClass}>Tanggal Beli *</label><input id={`buy-date-${item.id}`} required type="date" value={purchase.date} onChange={e => setPurchase({ ...purchase, date: e.target.value })} className={fieldClass} /></div><div className="flex gap-2"><button type="submit" disabled={!isShoppingPrice(purchasePrice) || !purchase.date} className={buttonClass}>Konfirmasi Beli</button><button type="button" onClick={() => setPurchase(null)} className="px-3 py-2 text-xs font-bold text-[#79738E]">Batal</button></div></form>}
      {item.notes && <p className="mt-3 p-3 rounded-xl bg-[#FCFBF8] border border-[#F0ECE4] text-xs text-[#79738E]">{item.notes}</p>}
    </article>)}
    <button onClick={onAddItem} className="w-full py-3.5 rounded-2xl bg-[#EEE9FF] text-[#6C4CF5] font-black text-sm inline-flex justify-center items-center gap-2"><Plus className="w-4 h-4" />Tambah Barang</button>
  </div>;
};
