import React, { useState } from 'react';
import { fieldClass, labelClass } from '../records/RecordEditor';
export interface CategoryAllocationInput { category: string; planned: number; spent?: number; icon: string; color: string; }
interface Props { isOpen: boolean; onClose: () => void; currentTotalBudget: number; currentCategories: CategoryAllocationInput[]; onSaveBudgetSetup: (total: number, categories: CategoryAllocationInput[]) => void; }
export const BudgetSetupModal: React.FC<Props> = props => props.isOpen ? <BudgetSetupForm {...props} /> : null;
const BudgetSetupForm: React.FC<Props> = ({ onClose, currentTotalBudget, currentCategories, onSaveBudgetSetup }) => {
  const [total, setTotal] = useState(String(currentTotalBudget));
  const [categories, setCategories] = useState(currentCategories);
  const valid = !!total.trim() && Number.isFinite(Number(total)) && Number(total) >= 0;
  return <div className="fixed inset-0 z-50 bg-black/40 backdrop-blur-xs flex items-end sm:items-center justify-center sm:p-4"><div className="absolute inset-0" onClick={onClose} /><form role="dialog" aria-modal="true" aria-labelledby="budget-setup-title" onSubmit={e => { e.preventDefault(); if (!valid) return; onSaveBudgetSetup(Number(total), categories); onClose(); }} className="relative w-full max-w-lg bg-white rounded-t-[32px] sm:rounded-[32px] p-6 max-h-[92vh] overflow-y-auto space-y-4"><div className="flex justify-between items-center"><h2 id="budget-setup-title" className="text-xl font-black text-[#292442]">Atur Budget</h2><button type="button" aria-label="Tutup" onClick={onClose}>✕</button></div><div><label htmlFor="budget-total" className={labelClass}>Total Budget (IDR) *</label><input id="budget-total" type="number" min="0" step="1" required value={total} onChange={e => setTotal(e.target.value)} className={fieldClass} /></div><details className="p-3 rounded-2xl bg-[#FCFBF8] border border-[#E7E2D8]"><summary className="text-sm font-black text-[#79738E] cursor-pointer">Budget per kategori (opsional)</summary><p className="mt-2 text-xs text-[#79738E]">Boleh dibiarkan kosong. Nilai ini hanya untuk rencana, bukan pengeluaran.</p><div className="mt-3 space-y-3">{categories.map(c => <div key={c.category}><label htmlFor={`category-budget-${c.category}`} className={labelClass}>{c.category}</label><input id={`category-budget-${c.category}`} type="number" min="0" value={c.planned || ''} onChange={e => setCategories(categories.map(x => x.category === c.category ? { ...x, planned: Number(e.target.value) || 0 } : x))} className={fieldClass} /></div>)}</div></details><div className="flex gap-2"><button type="button" onClick={onClose} className="flex-1 py-3 rounded-2xl bg-[#F5F3ED] text-[#79738E] font-bold">Batal</button><button type="submit" disabled={!valid} className="flex-1 py-3 rounded-2xl bg-gradient-to-r from-[#34236B] to-[#6C4CF5] text-white font-black disabled:opacity-40">Simpan Budget</button></div></form></div>;
};
